# Generated by Django 3.0.3 on 2020-02-21 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='topi',
            new_name='topic',
        ),
    ]
